### ISSUE TITLE
Control timing?

### ISSUE THREAD

**Issue by istvanvasil** [YerkoPalma/choo-animate#1]
Any way one can control the duration of the fades?
Thank you!

**Comment by YerkoPalma** [comment]
Hi 👋 
Fades, and any animation function isn't part of this package, so I assume you are talking about the example in readme. If that is the case, then you should look at the [animation-toolbox](https://github.com/YerkoPalma/animation-toolbox) module, as you can see, the `fade` animations get some parameters, that include delay. Since [choo-animate only pass the html element](https://github.com/YerkoPalma/choo-animate#var-store--animateopts), the default delay is applyed, so you should wrapp those functions

```js
var { fadeIn, fadeOut } = require('animation-toolbox')

var delay = 2000 // delay in ms, default is 1000 (1s)

var app = choo()
app.use(require('choo-animate')({
  animations: {
    fadeIn: function (el) {
      return fadeIn(el, delay)
    }
  }
}))
```

**Comment by istvanvasil** [comment]
I would like to use it as you guessed, to fade in and out when navigating between views. I will work from what you've described above. Thank you!

**Comment by istvanvasil** [comment]
This seems to work really well but for some reason I can't get fadeOut to work. Choo navigates away straight ahead and no before transition is applied. This happens even with the default example or by running the test provided. Running it in Chrome on OsX High Sierra.

A further bug would be that if choo-animate is used routes break in Safari and navigation stop working. Very much of a mood breaker. Am I missing some polyfill here? 

I am new to Choo and generally Javascript so sorry if these are very obvious questions. But if you have any input I would appreciate it.

Thank you.
